benchmark_id: credit_scoring-training_config-germain_credit_risk_v1.0.0
timestamp: '2025-10-06T03:32:53.916765+00:00'
model_architecture:
  model_type: CalificacionCrediticiaModel
  input_features: 26
  hidden_layers:
  - 128
  - 64
  - 64
  use_batch_norm: true
  activation_fn: ReLU
  dropout_rate: 0.1
  output_layer_neurons: 1
  total_parameters: 16449
training_configuration:
  optimizer: Adam
  learning_rate: 0.001
  weight_decay: 0.0001
  loss_function: BCEWithLogitsLoss
  use_pos_weight: true
  epochs_run: 13
  batch_size: 32
final_validation_metrics:
  accuracy: 0.675
  precision: 0.844
  recall: 0.6571
  f1: 0.739
  roc_auc: 0.7493
