version: 1.0.0

project_info:
  benchmark_id: credit_scoring-training_config-germain_credit_risk_v1.0.0
  description: Entrenamiento de MLP para puntaje crediticio

environment: venv

data_source:
  dataset_name: genia_services_csv_german_credit_risk_v1.0.0_training_5k_20250824
  data_path:
    dataset_path: ../../datasets/german_credit_risk.csv
    artifact_path: "model"
    preprocessor_filename: "german_credit_risk_preprocessor.joblib"
  version_tag: v1

preprocessing_params: N/A

model_config:
  model_name: "genia_services_mlp_credit_scoring_model_v1.0.0_20250824.pt"
  model_version: "v1.0.0"

  architecture:
    hidden_layers: [128, 64] # 2 capas ocultas, con n nodos en la primera y m nodos en la segunda 
    use_batch_norm: true
    activation_fn: "ReLU"
    dropout_rate: 0.2 # apaga el 20% de las neuronas de forma aleatoria
    
  classes:
    - "good"
    - "bad"

training_params:
  test_size: 0.2 # de los 1000 datos solo elegira 200 
  random_state: 42 # de manera aleatoria
  epochs: 100 # epocas de entrenamiento 
  batch_size: 32 # toma los primero 32 elementos del dataset y lo pasa a la red neuronal para el entrenamiento 

  optimizer:
    name: "Adam" #optimizador ADAM
    learning_rate: 0.001
    weight_decay: 0.0001
  
  loss_function:
    use_pos_weight: true # aniadir mayor peso a alguna caracteristica de mayor importancia (por ejemplo si es buen o mal pagador)

  scheduler: # cuando se quiere dejar de aprender el de saltos mas grandes/pequenios para encontrar min globales y no locales#
    name: "ReduceLROnPlateau"
    patience: 5
    factor: 0.5

  early_stopping: # cortamos entrenamiento
    patience: 10
    delta: 0.001

evaluation_params:
  batch_size: 1
  metrics:
    - accuracy
    - recall
    - f1_score
    - specificity
    - precision
  timing_metrics:
    - average_inference_time
    - average_processing_time
    - total_benchmark_time

  save_predictions: False
  save_failed_cases: True

mlflow_config:
  mlflow_project_name: "credit_scoring"
  mlflow_run_name_prefix: "credit_scoring-training_config-german_credit_risk_v100"
  mlflow_tags: ["credit_scoring", "mlp", "training"]


benchmark_specific: N/A